sudo: required
dist: trusty

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: change

before_install:
  - ./.travis.sh

addons:
  apt:
    packages:
      - valgrind
      - oraclejdk8
      - zip
      - zlib1g-dev
      - unzip
      - pkg-config

# TODO: Install buck on linux
script: 
  - bazel build :all && bazel test :all
