sudo: required

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang

dist: trusty

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - zlib1g-dev
      - libprotobuf-dev
      - protobuf-compiler
      - cmake
      - valgrind

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install protobuf;
    fi

script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake . && make && valgrind --error-exitcode=1 ./test/run_ut;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      cmake . && make && ./test/run_ut;
    fi
