sudo: required
dist: trusty

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: change

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then jdk_switcher use oraclejdk8; fi
  - ./.travis.sh

addons:
  apt:
    packages:
      - valgrind
      - oraclejdk8
      - zip
      - zlib1g-dev
      - unzip
      - pkg-config

# TODO: Install buck on linux
script: 
  - bazel build :all
  - ./bazel-bin/geo_base_test
  - if [ $TRAVIS_OS_NAME == "linux" ]; then valgrind --error-exitcode=1 ./bazel-bin/geo_base_test; fi
