sudo: required

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang
dist: trusty

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: always

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update;
      sudo apt-get install -y zlib1g-dev;
      sudo apt-get install -y libprotobuf-dev;
      sudo apt-get install -y protobuf-compiler;
      sudo apt-get install -y cmake;
      sudo apt-get install -y valgrind;
      cmake --version;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install protobuf;
      cmake --version;
    fi

script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake . && make VERBOSE=1 && valgrind --error-exitcode=1 ./test/run_ut
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      cmake . && make VERBOSE=1 && ./test/run_ut
    fi
