language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update && sudo apt-get install -y libprotobuf-dev;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update && brew install protobuf;
    fi

script: scons

branches:
  only:
    - master

os:
  - linux
  - osx
