sudo: required
dist: trusty

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - valgrind

script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake . && make && valgrind --error-exitcode=1 ./test/run_test;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      cmake . && make && ./test/run_test;
    fi
