sudo: required
dist: trusty

language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: change

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install buck;
    fi

addons:
  apt:
    packages:
      - valgrind

# TODO: Install buck on linux
script: 
  - if [ $TRAVIS_OS_NAME == linux ]; then
      buck test;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      buck test;
    fi
