language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update;
      sudo apt-get install -y zlib1g-dev;
      sudo apt-get install -y libprotobuf-dev;
      sudo apt-get install -y protobuf-compiler;
      sudo apt-get install -y scons;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install protobuf;
      brew install scons;
      g++ --version;
    fi

script: scons

branches:
  only:
    - master

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: change
