language: cpp

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update;
      sudo apt-get install -y zlib1g-dev;
      sudo apt-get install -y libprotobuf-dev;
      sudo apt-get install -y protobuf-compiler;
      sudo apt-get install -y cmake;
      sudo update-alternatives --config c++
      cmake --version;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      brew update;
      brew install protobuf;
      cmake --version;
    fi

script: 
  - cmake . && make && test/run_ut

branches:
  only:
    - master

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - urtashev@gmail.com
    on_success: change
    on_failure: always
